export const env = {
  UPLOADTHING_SECRET: process.env.UPLOADTHING_SECRET!,
  UPLOADTHING_APP_ID: process.env.UPLOADTHING_APP_ID!,
  GOOGLE_GENERATIVE_AI_API_KEY: process.env.GOOGLE_GENERATIVE_AI_API_KEY!,
}
